# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scf_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimpleContinuedFractionCalculatorForm(object):
    def setupUi(self, SimpleContinuedFractionCalculatorForm):
        SimpleContinuedFractionCalculatorForm.setObjectName("SimpleContinuedFractionCalculatorForm")
        SimpleContinuedFractionCalculatorForm.resize(450, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(SimpleContinuedFractionCalculatorForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(SimpleContinuedFractionCalculatorForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.form_expression_label = QtWidgets.QLabel(SimpleContinuedFractionCalculatorForm)
        self.form_expression_label.setObjectName("form_expression_label")
        self.gridLayout.addWidget(self.form_expression_label, 0, 0, 1, 1)
        self.form_expression_line_edit = QtWidgets.QLineEdit(SimpleContinuedFractionCalculatorForm)
        self.form_expression_line_edit.setObjectName("form_expression_line_edit")
        self.gridLayout.addWidget(self.form_expression_line_edit, 0, 1, 1, 1)
        self.form_depth_label = QtWidgets.QLabel(SimpleContinuedFractionCalculatorForm)
        self.form_depth_label.setObjectName("form_depth_label")
        self.gridLayout.addWidget(self.form_depth_label, 1, 0, 1, 1)
        self.form_depth_spin_box = QtWidgets.QSpinBox(SimpleContinuedFractionCalculatorForm)
        self.form_depth_spin_box.setObjectName("form_depth_spin_box")
        self.gridLayout.addWidget(self.form_depth_spin_box, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.form_submit_push_button = QtWidgets.QPushButton(SimpleContinuedFractionCalculatorForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_submit_push_button.sizePolicy().hasHeightForWidth())
        self.form_submit_push_button.setSizePolicy(sizePolicy)
        self.form_submit_push_button.setMaximumSize(QtCore.QSize(80, 20))
        self.form_submit_push_button.setObjectName("form_submit_push_button")
        self.verticalLayout.addWidget(self.form_submit_push_button)
        self.form_results_horizontal_line = QtWidgets.QFrame(SimpleContinuedFractionCalculatorForm)
        self.form_results_horizontal_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.form_results_horizontal_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.form_results_horizontal_line.setObjectName("form_results_horizontal_line")
        self.verticalLayout.addWidget(self.form_results_horizontal_line)
        self.result_label = QtWidgets.QLabel(SimpleContinuedFractionCalculatorForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_label.sizePolicy().hasHeightForWidth())
        self.result_label.setSizePolicy(sizePolicy)
        self.result_label.setObjectName("result_label")
        self.verticalLayout.addWidget(self.result_label)
        self.result_render_label = QtWidgets.QLabel(SimpleContinuedFractionCalculatorForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_render_label.sizePolicy().hasHeightForWidth())
        self.result_render_label.setSizePolicy(sizePolicy)
        self.result_render_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_render_label.setObjectName("result_render_label")
        self.verticalLayout.addWidget(self.result_render_label)

        self.retranslateUi(SimpleContinuedFractionCalculatorForm)
        QtCore.QMetaObject.connectSlotsByName(SimpleContinuedFractionCalculatorForm)

    def retranslateUi(self, SimpleContinuedFractionCalculatorForm):
        _translate = QtCore.QCoreApplication.translate
        SimpleContinuedFractionCalculatorForm.setWindowTitle(_translate("SimpleContinuedFractionCalculatorForm", "Calculator"))
        self.title_label.setText(_translate("SimpleContinuedFractionCalculatorForm", "Simple Continued Fraction Calculator"))
        self.form_expression_label.setText(_translate("SimpleContinuedFractionCalculatorForm", "Expression"))
        self.form_depth_label.setText(_translate("SimpleContinuedFractionCalculatorForm", "Depth"))
        self.form_submit_push_button.setText(_translate("SimpleContinuedFractionCalculatorForm", "Calculate"))
        self.result_label.setText(_translate("SimpleContinuedFractionCalculatorForm", "Result"))
        self.result_render_label.setText(_translate("SimpleContinuedFractionCalculatorForm", "Result Fraction will be rendered here"))
