# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'symbol_configuration_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SymbolConfigurationWindow(object):
    def setupUi(self, SymbolConfigurationWindow):
        SymbolConfigurationWindow.setObjectName("SymbolConfigurationWindow")
        SymbolConfigurationWindow.resize(400, 300)
        SymbolConfigurationWindow.setWindowTitle("Configure Symbols")
        self.verticalLayout = QtWidgets.QVBoxLayout(SymbolConfigurationWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.symbol_table_widget = QtWidgets.QTableWidget(SymbolConfigurationWindow)
        self.symbol_table_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.symbol_table_widget.setObjectName("symbol_table_widget")
        self.symbol_table_widget.setColumnCount(2)
        self.symbol_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.symbol_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.symbol_table_widget.setHorizontalHeaderItem(1, item)
        self.symbol_table_widget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.symbol_table_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_push_button = QtWidgets.QPushButton(SymbolConfigurationWindow)
        self.add_push_button.setObjectName("add_push_button")
        self.horizontalLayout.addWidget(self.add_push_button)
        self.remove_push_button = QtWidgets.QPushButton(SymbolConfigurationWindow)
        self.remove_push_button.setObjectName("remove_push_button")
        self.horizontalLayout.addWidget(self.remove_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SymbolConfigurationWindow)
        QtCore.QMetaObject.connectSlotsByName(SymbolConfigurationWindow)

    def retranslateUi(self, SymbolConfigurationWindow):
        _translate = QtCore.QCoreApplication.translate
        item = self.symbol_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("SymbolConfigurationWindow", "Symbol"))
        item = self.symbol_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("SymbolConfigurationWindow", "Value"))
        self.add_push_button.setText(_translate("SymbolConfigurationWindow", "Add"))
        self.remove_push_button.setText(_translate("SymbolConfigurationWindow", "Remove"))
